feat(vscodePlugin): add i18n
Tencent/cherry-markdown pull request #1010
Opened 2024-12-20 20:50 UTC by RSS1102

![image](https://github.com/user-attachments/assets/7ed5210d-6f16-4f91-9699-8c9bc8d83d53)

2024-12-22 19:54 UTC, RSS1102 commented
1. 支持了对于 vscode 插件配置支持了俄语 `ru` 。
2. [vscode-l10n](https://github.com/microsoft/vscode-l10n/tree/1cbcbf1e5de3156067e946cef713f0eb702dd983?tab=readme-ov-file#vscodel10nt) 中提到最近 vscode 版本支持应该在 `>1.73` , 则提高 `engines.vscode` 支持版本。
3. [ ] 发现`cherry-markdown` 工具栏部分语言没有进行多语言化/多语言化不全，应该进行一次集中修正，并尝试添加日语多语言化(vscode plugin 已添加对于日语的支持)。
4. [ ] 添加俄语`readme` 对齐。

2024-12-23 01:28 UTC, sunsonliu requested changes

2024-12-23 01:28 UTC, sunsonliu commented on vscodePlugin/web-resources/scripts/index.js
> +};
不用那么多，目前cherry只提供了中、英、俄三中语言。。可以看这里：https://github.com/Tencent/cherry-markdown/tree/main/src/locales

2024-12-23 01:54 UTC, RSS1102 commented on vscodePlugin/web-resources/scripts/index.js
> +};
要加上日语嘛？

顺便把一些没有进行多语言的功能给添加上？

![image](https://github.com/user-attachments/assets/3332178e-bfd8-49e9-8c50-63dc58840e9f)

2024-12-23 01:55 UTC, sunsonliu commented on vscodePlugin/web-resources/scripts/index.js
> +};
不需要加上日语哈

2024-12-23 02:04 UTC, sunsonliu approved these changes

2024-12-23 02:07 UTC, merged