fix: Link hook对url进行排他处理
Tencent/cherry-markdown pull request #260
Opened 2022-07-03 11:58 UTC by object-kaz

针对 #235 的BUG，给Link hook 的url添加了排他语法

2022-07-04 03:06 UTC, lyngai requested changes

2022-07-04 03:06 UTC, lyngai commented on src/core/hooks/Link.js
> +        const key = this.pushCache(processedURL, ParagraphBase.IN_PARAGRAPH_CACHE_KEY_PREFIX + hash);
url 缓存的思路正确，但在这里的做法不合适。可以参考项目内 `cherry-inner` 协议短链的相关代码，看看是否能解决这个问题。

2022-07-05 11:17 UTC, object-kaz commented on src/core/hooks/Link.js
> +        const key = this.pushCache(processedURL, ParagraphBase.IN_PARAGRAPH_CACHE_KEY_PREFIX + hash);
参考了下 Image hooks，修改了一版

2022-07-06 03:38 UTC, lyngai approved these changes
LGTM

2022-07-06 03:52 UTC, merged