feat: 实现快捷键显示/隐藏toolbar #268
Tencent/cherry-markdown pull request #285
Opened 2022-08-01 15:52 UTC by ufec

#268 
模仿官方注册的一个快捷键 `Ctrl + q` 来实现显示隐藏状态栏，但并不影响其他 HOOKS，例如`Ctrl-1`

2022-08-02 02:46 UTC, lyngai requested changes

2022-08-02 02:46 UTC, lyngai commented on src/toolbars/hooks/Insert.js
> +        shortcutKey: 'Mod-q',
不建议使用 q，在 mac 下 `⌘+Q` 是退出程序的快捷键。

2022-08-02 03:02 UTC, ufec commented on src/toolbars/hooks/Insert.js
> +        shortcutKey: 'Mod-q',
不好意思，Windows开发，没注意这点
当时再chrome下测试，`Ctrl + 1`，默认是切换标签页，但在页面上监听了快捷键，默认会执行监听事件，不会触发切换标签页，我就以为应该没事
那换成 `Ctrl 0` 如何，目前没有这个快捷键，应该也不会有

2022-08-02 06:48 UTC, sunsonliu commented on src/toolbars/hooks/Insert.js
> +
![image](https://user-images.githubusercontent.com/998441/182309713-d6275a22-48f6-4ec9-b3aa-b48834375f0f.png)
- 不是特别建议在insert里实现该功能哈，这个更像是设置（`toolbars/hooks/Settings.js`）的职责。
- 另外这里展示、隐藏toolbar还需要修改下Cherry.js 里的状态哈（虽然目前还没啥用。。。）

2022-08-02 08:39 UTC, ufec commented on src/toolbars/hooks/Insert.js
> +
起初考虑到在`Settings`里实现的话，要按照`insert`里面实现注册快捷键的步骤，柑橘步骤有些重复就没有那么做，但考虑到设计层面确如你所说，刚重新提交了一版
至于修改 `cherry.status` 我第二次提交附加了Event，但是没有效果，我找到了问题所在，这个或许是个bug，需要与你们进一步沟通方能确定，如果确实是个`bug`，待我提交修复后，自然就会自动同步(我在本地试验过，确实可行)

2022-08-04 11:32 UTC, lyngai commented on src/toolbars/hooks/Insert.js
> +        shortcutKey: 'Mod-q',
可以试试 <kbd>Mod + Shift + B</kbd>。也就是 <kbd>Ctrl / Cmd + Shift + B</kbd>。

2022-08-04 12:37 UTC, ufec commented on src/toolbars/hooks/Insert.js
> +        shortcutKey: 'Mod-q',
经测试 `Shift`键并不会被识别
这个我改为`Ctrl 0`了，按照功能在`Setting`

2022-08-04 12:53 UTC, ufec commented on src/toolbars/hooks/Insert.js
> +        shortcutKey: 'Mod-q',
无法识别`Shift` 组合键 这仍然是个`Bug`，如果我提交修复会与本次提交的目的有歧义，并且在chrome中`Ctrl / Cmd + Shift + B` 这个快捷键是用于 `打开/关闭 浏览器标签的显示`
我认为`Ctrl + 0` 比较适合的原因：
- 它不是系统快捷键
- 它不是浏览器快捷键
- 它不与已有快捷方式冲突
- 它只有两个键，足够快捷
望采纳

2022-08-04 13:54 UTC, lyngai commented on src/toolbars/hooks/Insert.js
> +        shortcutKey: 'Mod-q',
> 无法识别`Shift` 组合键 这仍然是个`Bug`，如果我提交修复会与本次提交的目的有歧义

合理，shift 组合键无法使用可以另提一个 bug report 以便跟进。

> 在chrome中`Ctrl / Cmd + Shift + B` 这个快捷键是用于 `打开/关闭 浏览器标签的显示

`Ctrl + 0` 确实没有问题。

个人认为按以下两个思路去设计快捷键能得出更好的方案：

1. **语义化**，比如 <kbd>Ctrl / Cmd + H</kbd> 多用于隐藏(**H**ide)操作、<kbd>Ctrl / Cmd + O</kbd> 多用于打开(**O**pen)操作、<kbd>Cmd + Q</kbd> 用于退出(**Q**uit) macOS 的应用、<kbd>Win + L</kbd> 用于锁定(**L**ock) Windows计算机...等等。

2. **近似功能键覆盖**，很显然双键组合语义化的快捷键大部分都被占用了，这个情况下可以考虑覆盖近似功能的快捷键，比如：使用了虚拟列表技术去展示的上万行文本，这里使用的也是与网页原本冲突的快捷键 `Ctrl / Cmd + F`。当然，这个例子也因为使用了虚拟列表，导致原有的搜索功能无法得到预期结果，才进行的覆盖。

VSCode 下 `Ctrl / Cmd + B` 也是用来隐藏侧边栏的，但在文本编辑场景下 B 更多表示 `Bold` 加粗。所以上面才推荐另加一个组合键 Shift。正巧浏览器的 `Ctrl / Cmd + Shift + B` 也是用来隐藏书签栏，功能近似，所以只要能覆盖掉浏览器的默认行为，且只有在编辑器的编辑区域激活时才触发快捷键，按照这个原则是没问题的。

2022-08-04 13:58 UTC, lyngai approved these changes

2022-08-04 14:22 UTC, ufec commented on src/toolbars/hooks/Insert.js
> +        shortcutKey: 'Mod-q',
嗯嗯，合掉这个之后，待我提交那个`Shift`的问题之后，可以再做商榷

2022-08-05 07:52 UTC, lyngai requested changes

2022-08-05 07:52 UTC, lyngai commented on src/toolbars/Toolbar.js
> +  if (event.key && event.key.toLowerCase() != 'shift') {
eslint 问题关注一下。需要修复。

2022-08-05 08:00 UTC, ufec commented on src/toolbars/Toolbar.js
> +  if (event.key && event.key.toLowerCase() != 'shift') {
好的，已提交修复

2022-08-05 10:32 UTC, merged