feat: 多行SETEXT header
Tencent/cherry-markdown pull request #297
Opened 2022-08-05 14:35 UTC by perry-C

2022-08-05 15:52 UTC, sunsonliu commented
这里是为了解决行内排他语法后的标题语法失效的问题么，没有特别看懂这里改动的效果

2022-08-06 04:03 UTC, lyngai requested changes
语法正则不应包含自身的缓存匹配，另外考虑实现思路。

2022-08-06 06:45 UTC, perry-C commented
> 这里是为了解决行内排他语法后的标题语法失效的问题么，没有特别看懂这里改动的效果

是的，有没有更好的规避排他语法的方法？

2022-08-06 06:46 UTC, perry-C commented
> 语法正则不应包含自身的缓存匹配，另外考虑实现思路。

好的 我修改一下

2022-08-14 17:59 UTC, closed without merging