快捷键响应的onclick事件无返回值报错 #296
Tencent/cherry-markdown pull request #298
Opened 2022-08-05 14:40 UTC by ufec

错误分析：
仓库中 [MenuBase.js#L237](https://github.com/Tencent/cherry-markdown/blob/dev/src/toolbars/MenuBase.js#L237) 此行代码用于将当前选中元素替换为快捷键生成的内容，
会对传入的第一个参数(字符串数组)每个字符串执行一个`split`函数，不反悔或返回不是字符串自然报错

2022-08-05 14:42 UTC, ufec commented
#296

2022-08-06 03:43 UTC, lyngai requested changes

2022-08-06 03:43 UTC, lyngai commented on src/toolbars/MenuBase.js
>      const ret = selections.map((selection) => this.onClick(selection, key));
下面的修改将简单的事情变复杂了，过滤一下非字符串元素就好了。

```ts
const ret = selections.map(...).filter((v) => typeof v === 'string');
```

2022-08-06 03:54 UTC, ufec commented on src/toolbars/MenuBase.js
>      const ret = selections.map((selection) => this.onClick(selection, key));
确实，还有个lint错误

2022-08-06 03:58 UTC, ufec commented on src/toolbars/MenuBase.js
>      const ret = selections.map((selection) => this.onClick(selection, key));
@sunsonliu 说先挂着，等重构这部分代码

2022-08-07 17:53 UTC, sunsonliu commented on src/toolbars/MenuBase.js
>      const ret = selections.map((selection) => this.onClick(selection, key));
增加个 `this.updateMarkdown = false;` 的配置就好了（已给settings增加了这个配置）

2022-08-08 07:24 UTC, ufec commented on src/toolbars/MenuBase.js
>      const ret = selections.map((selection) => this.onClick(selection, key));
```
if (!this.bubbleMenu && this.updateMarkdown) {
  // 非下拉菜单按钮保留selection
  this.editor.editor.replaceSelections(ret, 'around');
  this.editor.editor.focus();
}
```
但这个好像是`insert hook` 里增加这个配置吧

考虑边界的话处理一下应该也是有必要的

2022-08-08 07:29 UTC, ufec commented on src/toolbars/MenuBase.js
>      const ret = selections.map((selection) => this.onClick(selection, key));
```
if (!this.bubbleMenu && this.updateMarkdown) {
  // 非下拉菜单按钮保留selection
  this.editor.editor.replaceSelections(ret, 'around');
  this.editor.editor.focus();
}
```
但这个好像是`insert hook` 里增加这个配置吧

考虑边界的话处理一下应该也是有必要的

2022-08-08 12:10 UTC, sunsonliu commented on src/toolbars/MenuBase.js
>      const ret = selections.map((selection) => this.onClick(selection, key));
![image](https://user-images.githubusercontent.com/998441/183414729-4d32671c-b844-46fc-aa79-f93fededbc0d.png)
额，理论上onClick函数返回空的时候是不做任何事情的，似乎也不需要做额外的处理。。

2022-08-08 13:56 UTC, ufec commented on src/toolbars/MenuBase.js
>      const ret = selections.map((selection) => this.onClick(selection, key));
哦哦，我看的时候你还没merge，看的旧版的

2023-08-13 05:30 UTC, closed without merging