feat(Suggester): Suggester扩展 #430
Tencent/cherry-markdown pull request #473
Opened 2023-06-18 05:57 UTC by ufec

2023-06-19 03:27 UTC, sunsonliu requested changes

2023-06-19 03:27 UTC, sunsonliu commented on examples/scripts/suggester-demo.js
> +        suggester: [
这个联想的能力有没有可能放到系统默认的能力里，然后通过`Cherry.config.js`来进行配置（最简单的配置就是true启用，false不启用）

2023-06-19 03:27 UTC, sunsonliu commented on src/toolbars/hooks/Table.js
> +  onClick(selection, shortKey = '', left = 0, top = 0) {
不建议增加这两个参数，一般第三个参数是clickEvent，如果有定位不准的情况，可以考虑通过`this.dom`来进行判断来调整获取位置的逻辑

2023-06-19 04:57 UTC, ufec commented on examples/scripts/suggester-demo.js
> +        suggester: [
相当于 `/` 这个是系统默认的？由用户决定是否开启？其他的还是交给客户联想能力还是交给用户

2023-06-20 10:56 UTC, sunsonliu commented on examples/scripts/suggester-demo.js
> +        suggester: [
> 相当于 `/` 这个是系统默认的？由用户决定是否开启？其他的还是交给客户联想能力还是交给用户

嗯嗯嗯，是嘞哈，我们好不容易做的功能当然是希望越多的人使用嘛

2023-06-20 10:58 UTC, sunsonliu commented
![image](https://github.com/Tencent/cherry-markdown/assets/998441/1eec0d8f-aa82-4a33-8e51-a328f535ce8c)
这里的报错可能也要关注下

2023-06-26 04:35 UTC, merged