feat: 有序列表、无序列表、checklist支持所见即所得编辑 #543
Tencent/cherry-markdown pull request #553
Opened 2023-08-29 12:07 UTC by ufec

实现 有序列表、无序列表、checklist支持所见即所得编辑 #543

2023-08-30 06:26 UTC, sunsonliu requested changes

2023-08-30 06:26 UTC, sunsonliu commented on src/sass/previewer.scss
> +  .cherry-previewer-list-content-hander__input {
这个样式没用了吧

2023-08-30 06:26 UTC, sunsonliu commented on src/core/hooks/List.js
> +      const str = `<p contenteditable="plaintext-only">${child.strs.join('<br>')}</p>`;
不建议修改engine，因为有些业务只用engine.makeHtml(md)来把md内容解析成html，并把html展示到他们的页面上。如果修改这里就会导致他们渲染到页面上的内容可以编辑了
建议还是在perviewer里做文章，比如鼠标hover到previewer的列表时动态增加这个属性

2023-08-30 06:26 UTC, sunsonliu commented on src/toolbars/PreviewerBubble.js
>    getValueWithoutCode() {
这里是不是也可以替换成新写的 regexp.js里的getValueWithoutCode

2023-08-30 11:38 UTC, ufec commented on src/toolbars/PreviewerBubble.js
>    getValueWithoutCode() {
ok

2023-08-30 11:38 UTC, ufec commented on src/sass/previewer.scss
> +  .cherry-previewer-list-content-hander__input {
哦对，这个忘记删了

2023-08-31 05:30 UTC, ufec commented on src/core/hooks/List.js
> +      const str = `<p contenteditable="plaintext-only">${child.strs.join('<br>')}</p>`;
这里我重新看了下，如果不是默认加上那就会存在不能连续输入的问题：在右侧预览区域更新内容后，同步到左边编辑区，但编辑区域更新会触发dom渲染，导致属性丢失，无法连续编辑
或许可以在makeHtml的时候，将生成的html中的 contenteditable属性去掉？
又或者加一个配置项，默认不支持所见即所得，开启后支持

2023-08-31 16:23 UTC, sunsonliu requested changes

2023-09-01 16:14 UTC, ufec commented on src/core/hooks/List.js
> +      const str = `<p contenteditable="plaintext-only">${child.strs.join('<br>')}</p>`;
这么做是可以，但是不能连续输入有点儿难受，先搞一个看看效果吧

2023-09-03 16:08 UTC, sunsonliu commented on src/core/hooks/List.js
> +      const str = `<p contenteditable="plaintext-only">${child.strs.join('<br>')}</p>`;
咦。。。讲道理右侧停止渲染更有利于连续输入呀

2023-09-04 11:41 UTC, sunsonliu approved these changes
LGTM

2023-09-04 11:53 UTC, merged