fix: 修复editOnly模式下切换主题导致的样式bug
Tencent/cherry-markdown pull request #636
Opened 2023-11-10 09:46 UTC by eyebrowkang

2023-11-20 09:15 UTC, sunsonliu requested changes

2023-11-20 09:15 UTC, sunsonliu commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
抱歉刚看到这个PR（冰天雪地只穿裤衩后空翻无缝接360旋体跪地致歉）。。
不过建议继续沿用原来的思路，及 `先去掉旧的class`，`再增加新的class`，这样的好处是当`replacer`没有命中时，也能增加新的class

2023-11-20 13:34 UTC, nenge123 commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
为啥不是
```
 $cherry.wrapperDom.classList.remove(old); //返回true时移除成功
 $cherry.wrapperDom.classList.add(new); //返回true时添加成功
 $cherry.wrapperDom.classList.toggle(active);//有就删掉 没有就添加 返回true时添加成功
 ````
className太不靠谱 例如存在相似样式岂不是翻车

2023-11-21 01:45 UTC, eyebrowkang commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
> 抱歉刚看到这个PR（冰天雪地只穿裤衩后空翻无缝接360旋体跪地致歉）。。 不过建议继续沿用原来的思路，及 `先去掉旧的class`，`再增加新的class`，这样的好处是当`replacer`没有命中时，也能增加新的class

确实原来的思路要更加严谨一些，说到具体的实现，我认为遍历classList, 删除`theme__` 开头的所有类名，遍历结束后再`classList.add(new)`，是不是会更加好一点，我个人也觉得操纵字符串的风险会大一些

2023-11-21 02:14 UTC, eyebrowkang commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
不过话说回来，上面的方法好像太繁琐了，而且性能方面应该也是有差距的，我稍等先提交一个直接替换className的吧，看下是否OK

2023-11-21 10:20 UTC, sunsonliu commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
弱弱问下，你是想解决 https://github.com/Tencent/cherry-markdown/issues/650#issuecomment-1820577652 这个问题么？如果是的话，该问题已解决哈，见 https://github.com/Tencent/cherry-markdown/commit/30be078aec720a69b160e9cb54121481d21d1c7b

2023-11-22 02:31 UTC, eyebrowkang commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
提这个PR确实是为了修复`changeTheme`函数的bug，解决就OK。

BTW, 直接替换成空格的话，多切换几次会有一堆空格在className里面吧

2023-11-22 02:31 UTC, closed without merging

2023-11-22 05:31 UTC, sunsonliu commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
> 提这个PR确实是为了修复`changeTheme`函数的bug，解决就OK。
> 
> BTW, 直接替换成空格的话，多切换几次会有一堆空格在className里面吧

不会的哈，如果命中正则才会被替换成空格，正则里首先匹配的就是`空格+theme__xxx`，所以是不会产生无限多空格的，如果实在不放心还可以在最后加个兜底逻辑 `className.replace(/ {2,}/g, ' ')`

2023-11-22 07:06 UTC, eyebrowkang commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
额，我说会有一堆空格是因为这个正则`/ theme__[^ $]+?( |$)/g`会匹配两种情况，theme类在中间和theme类在末尾，前者没有问题，实际上述的bug也是因为没有替换为空格导致的；后者则会使得replace后的字符串末尾多出一个空格，然后由于`newClass`的开头又有一个空格，所有就多了一个，那么在此基础之上多切换几次就有很多个空格了。

我语言描述得可能不好，你可以直接实际试一下。

2023-11-22 07:34 UTC, sunsonliu commented on src/utils/config.js
> +  $cherry.wrapperDom.className = $cherry.wrapperDom.className.replace(reg, replacer);
确实。。我回来再加个兜底逻辑吧，防止出现多个连续空格，感谢提醒~~