refactor(list): implement list with tree
Tencent/cherry-markdown pull request #76
Opened 2021-12-27 09:46 UTC by jiawei686

2021-12-28 03:18 UTC, humyfred approved these changes
LGTM

2021-12-28 03:18 UTC, merged

2021-12-28 03:19 UTC, lyngai requested changes

2021-12-28 03:19 UTC, lyngai commented on src/core/hooks/List.js
>      this.intentSpace = this.config.intentSpace > 0 ? this.config.intentSpace : 2;
`Math.max(this.config.intentSpace, 2)`

2021-12-28 03:19 UTC, lyngai commented on src/core/hooks/List.js
>      this.intentSpace = this.config.intentSpace > 0 ? this.config.intentSpace : 2;
intentSpace 是不是拼写错误？ 应该是 indentSpace？

2021-12-28 03:19 UTC, lyngai commented on src/core/hooks/List.js
> +        } else if (space < lastSpace + this.intentSpace + 4) {
魔术数字 4 出现了多次，代表的是什么含义？

2021-12-28 03:26 UTC, jiawei686 commented on src/core/hooks/List.js
>      this.intentSpace = this.config.intentSpace > 0 ? this.config.intentSpace : 2;
收到，感谢！我修改下这里~

2021-12-28 03:29 UTC, jiawei686 commented on src/core/hooks/List.js
> +        } else if (space < lastSpace + this.intentSpace + 4) {
有道理，我定义一个常量～commonmark好像意思是无序列表这种(-)一位的list marker吸收W(=1)+N(1 ≤ N ≤ 4)个空格做为缩进
我在这里试了下
https://spec.commonmark.org/dingus/?text=-%20foo%0A%20%20-%20bar%0A%20%20%20%20-%20baz%0A%20%20%20%20%20%20-%20boo%0A

2021-12-30 06:14 UTC, humyfred reviewed
LGTM

2021-12-30 06:16 UTC, lyngai reviewed
LGTM