ADD: localization (Russian)
Tencent/cherry-markdown pull request #875
Opened 2024-08-19 13:08 UTC by evgip

Hello. Thanks for the good editor.

Added Russian localization.

2024-08-19 13:08 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/cherry-markdown?pullRequest=875) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/cherry-markdown?pullRequest=875) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/cherry-markdown?pullRequest=875) it.</sub>

2024-08-20 01:14 UTC, sunsonliu requested changes

2024-08-20 01:14 UTC, sunsonliu commented on src/locales/index.js
> +  ru_RU: ruRU,
`ruRU`>>`ruRu`

2024-08-20 02:54 UTC, sunsonliu approved these changes
LGTM

2024-08-20 02:59 UTC, merged